name: "💡 Feature Request"
description: Suggest a feature for Qusto Analytics core engine
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!

        **Important:** This repository is for the **open-source Qusto Analytics core**.

        Premium features (funnels, AI tracking, attribution) are developed in private repositories.
        Consider whether your feature belongs in the open-source core or would be better as a premium feature.

        [Documentation](https://docs.qusto.io) | [Discussions](https://github.com/qusto-io/qusto-ce/discussions)

  - type: dropdown
    id: feature-scope
    attributes:
      label: Feature Scope
      description: Where should this feature live?
      options:
        - Open-source core (this repo)
        - Premium feature (Qusto Cloud only)
        - Not sure
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ### Open Source vs Premium Guidelines

        **Belongs in open-source core:**
        - Essential for basic analytics functionality
        - Self-hosting improvements
        - Dashboard UI enhancements
        - Core API improvements
        - Privacy/GDPR features
        - General performance optimizations

        **Likely belongs in premium:**
        - E-commerce specific tracking (funnels, cart analysis)
        - AI/ML-based features
        - Advanced attribution models
        - Enterprise SSO/team features
        - Cloud-specific infrastructure

        ---

  - type: checkboxes
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and discussions to make sure this hasn't been requested
          required: true
        - label: I have considered whether this belongs in the open-source core or premium features
          required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like
      placeholder: Describe the feature you're proposing
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why do you need this feature? What problem does it solve?
      placeholder: |
        As a [type of user], I want [feature] so that [benefit].

        Currently I have to [workaround], which is problematic because [reason].
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: If you have ideas about how to implement this, share them here
      placeholder: |
        Describe your proposed solution or approach.

        Include any technical details, UI mockups, or API designs if relevant.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: |
        Describe any alternative solutions or features you've considered.

        Why wouldn't these alternatives work for your use case?

  - type: textarea
    id: open-source-justification
    attributes:
      label: Why Open Source?
      description: Why should this be in the open-source core rather than a premium feature?
      placeholder: |
        Explain why this feature should be available to all users, including self-hosted installations.

        Consider:
        - Is this essential for basic analytics?
        - Would this benefit the broader community?
        - Is this a privacy/compliance requirement?

  - type: dropdown
    id: contribution
    attributes:
      label: Would you be willing to contribute this feature?
      description: Let us know if you'd like to implement this yourself
      options:
        - "Yes, I'd like to implement this"
        - "Yes, but I'd need guidance"
        - "No, I'm just suggesting the idea"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request
